workflows:
  ios-app-store:
    name: iOS App Store
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: kavaid
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.onbir.kavaid
      groups:
        - a # Your group of environment variables
      flutter: 3.19.6 # Pin to a specific stable version for consistency
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages and create helper files
        script: flutter pub get
      - name: Deep clean before build
        script: |
          flutter clean
          rm -rf .ios
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec
          flutter pub get
          flutter build ios --no-codesign
          cd ios
          pod install
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for App Store
        script: flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - kavaid