workflows:
  ios-test-ipa:
    name: iOS Test IPA (Unsigned)
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          cd Payload
          zip -r ../Kavaid-Test.ipa .
          cd ..
          echo "=== IPA oluşturuldu ==="
          ls -la *.ipa
    artifacts:
      - build/ios/iphoneos/Kavaid-Test.ipa
    publishing:
      email:
        recipients:
          - ebubekirkul6153@gmail.com
        notify:
          success: true
          failure: false

  # Workflow for releasing to the App Store
  ios-app-store-release:
    name: iOS App Store Release
    integrations:
      app_store_connect: default
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials # Codemagic UI'da tanımlanacak grup
    scripts:
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build iOS App
        script: | 
          flutter build ipa --release \
            --export-options-plist=$XCODE_EXPORT_OPTIONS_PATH
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration

        submit_to_testflight: true # İsteğe bağlı, doğrudan TestFlight'a gönderir
        beta_groups: # İsteğe bağlı, belirli test gruplarına atar
          - Kavaid Testers