workflows:
  ios-app-store:
    name: iOS App Store
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: kavaid
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.onbir.kavaid
      groups:
        - a # Your group of environment variables
      flutter: 3.19.6 # Pin to a specific stable version for consistency
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Clean and Regenerate iOS platform
        script: |
          rm -rf ios
          flutter create --platforms=ios .
      - name: Force create correct Podfile
        script: |
          cat << EOF > ios/Podfile
# Copyright 2014 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

uncomment_if_needed(self)

flutter_application_path = '..'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(flutter_application_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
EOF
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for App Store
        script: flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - kavaid