workflows:
  ios-app-store:
    name: iOS App Store
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: kavaid
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.onbir.kavaid
      groups:
        - a # Your group of environment variables
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths: []
    scripts:
      - name: Ultimate iOS Build Script
        script: |
          set -e
          echo "--- Repairing iOS Project Files ---"
          flutter create . --platforms=ios
          echo "--- Verifying Flutter Environment ---"
          flutter doctor -v
          echo "--- Cleaning Project ---"
          flutter clean
          echo "--- Reinstalling CocoaPods ---"
          sudo gem uninstall cocoapods -a -x && sudo gem install cocoapods
          echo "--- Installing FFI for M1 ---"
          sudo arch -x86_64 gem install ffi
          echo "--- Upgrading Flutter Packages ---"
          flutter pub upgrade
          echo "--- Generating iOS Project Files ---"
          flutter build ios --no-codesign
          echo "--- Verifying Helper File Creation ---"
          ls -la ios/Flutter
          echo "--- Performing Aggressive Pod Cleaning and Installation ---"
          cd ios
          rm -rf Pods Podfile.lock .symlinks Flutter/Flutter.framework Flutter/Flutter.podspec
          pod deintegrate
          arch -x86_64 pod install --repo-update
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for App Store
        script: flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - kavaid