workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: 15.2
      cocoapods: default
    cache:
      cache_paths: []
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Runner
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build iOS for release
        script: |
          flutter build ios --release --no-codesign
