workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: 1.16.2
    cache:
      cache_paths: []
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Runner
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Show AppDelegate content for debugging
        script: |
          echo "--- Displaying AppDelegate.swift content ---"
          cat ios/Runner/AppDelegate.swift
          echo "------------------------------------------"
      - name: Build iOS for release
        script: |
          flutter build ios --release --no-codesign
