workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: 1.16.2
      ios_signing:
        distribution_type: development  # Change to 'app_store' for App Store builds
        bundle_identifier: com.onbir.kavaid
    cache:
      cache_paths: []
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Runner
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Show AppDelegate content for debugging
        script: |
          echo "--- Displaying AppDelegate.swift content ---"
          cat ios/Runner/AppDelegate.swift
          echo "------------------------------------------"
      - name: Build iOS
        script: |
          flutter build ipa --release --export-options-plist=/tmp/ExportOptions.plist
      - name: Create ExportOptions.plist
        script: |
          cat > /tmp/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>\$TEAM_ID</string>
              <key>uploadBitcode</key>
              <false/>
              <key>compileBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - ebubekirkul6153@gmail.com
        notify:
          success: true
          failure: true

  simulator-preview-workflow:
    name: Flutter iOS Simulator Preview
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build Flutter app for simulator
        script: flutter build ios --simulator --debug
    artifacts:
      - build/ios/iphonesimulator/*.app
