// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'kavaid-2f778',
    authDomain: 'kavaid-2f778.firebaseapp.com',
    databaseURL: 'https://kavaid-2f778-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kavaid-2f778.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkGrJMttVYGiCDdHMzCUQBw6O9ROAIwKE',
    appId: '1:732976641832:android:eb3cf0eeef274ac6ad821d',
    messagingSenderId: '732976641832',
    projectId: 'kavaid-2f778',
    databaseURL: 'https://kavaid-2f778-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kavaid-2f778.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'kavaid-2f778',
    databaseURL: 'https://kavaid-2f778-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kavaid-2f778.appspot.com',
    iosBundleId: 'com.onbir.kavaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: '1:123456789:macos:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'kavaid-2f778',
    databaseURL: 'https://kavaid-2f778-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kavaid-2f778.appspot.com',
    iosBundleId: 'com.onbir.kavaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: '1:123456789:windows:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'kavaid-2f778',
    databaseURL: 'https://kavaid-2f778-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kavaid-2f778.appspot.com',
  );
} 