
platform :ios, '13.0'

flutter_application_path = File.expand_path('../..', __FILE__)
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
