name: Flutter iOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies
        run: flutter pub get

      - name: Clean and build iOS
        run: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign

      # Sertifika ve profil yükleme
      - name: Install certificate and provisioning profile
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          mkdir -p ~/certs
          echo "${{ secrets.IOS_CERTIFICATE_P12 }}" | base64 --decode > ~/certs/cert.p12
          echo "${{ secrets.IOS_PROVISION_PROFILE }}" | base64 --decode > ~/certs/profile.mobileprovision
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import ~/certs/cert.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ~/certs/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build IPA
        run: |
          cd ios
          pod install
          cd ..
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
